displayName: State Geo Block Middleware
type: middleware
import: github.com/vikewoods/traefik-plugin-state-geo

summary: Blocks all traffic outside of US and requests by US state using MaxMind GeoLite2 and supports custom block pages.

testData:
  blockedStates:
    - CA
    - NY
  whitelistedIPs:
    - 1.2.3.4
  whitelistedPaths:
    - /health
  templateHTML: |
    <!doctype html>
    <html>
      <body>
        <h1>Access denied</h1>
        <p>State: {{STATE}}</p>
      </body>
    </html>
  failOpen: true